name: Passo 2 # Fazer commit de um arquivo

# Verifica se o aprendiz completou as tarefas para o passo 2.
# - Dispara quando o usuário faz um push para o branch 'my-first-branch' e modifica o arquivo 'PROFILE.md'.
# - Se todas as verificações passarem, o workflow é desativado para não ser executado novamente. Assim, o selo de status do workflow mudará para verde.

on:
  push:
    branches:
      - "my-first-branch"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/3-open-a-pull-request.md"


jobs:
  find_exercise:
    name: Encontrar Issue do Exercício
    uses: dev-pods/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.1.0

  check_step_work:
    name: Verificar trabalho do passo
    runs-on: ubuntu-latest
    needs: find_exercise
    if: |
      !github.event.repository.is_template
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter modelos de resposta
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.0


      - name: Atualizar comentário - verificando trabalho
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # INÍCIO: Verificar exercício prático

      # Nada para verificar. Criar o arquivo PROFILE.md é suficiente.

      # FIM: Verificar exercício prático


      - name: Construir mensagem - passo finalizado
        id: build-message-step-finish
        uses: skills/action-text-variables@v1
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number=3

      - name: Atualizar comentário - passo finalizado
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "${{ steps.build-message-step-finish.outputs.updated-text }}" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_next_step_content:
    name: Publicar conteúdo do próximo passo
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter modelos de resposta
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.0

      - name: Criar comentário - adicionar conteúdo do passo
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.STEP_3_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar comentário - observando o progresso
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Desativar workflow atual e ativar o próximo
        run: |
          gh workflow disable "Passo 2"
          gh workflow enable "Passo 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
